confiq.yml
SplitScreen-Me/splitscreenme-discordbot pull request #44
Opened 2022-06-18 23:58 UTC by errorline99

tell me if there is something wrong i hope i did it right (this is my first open source contribution )

2022-06-19 00:21 UTC, Snailedlt requested changes
Hi this is Great!
Welcome to the open source community, and thank you very much for contributing!

This is mostly looking good (especially for your first contribution)!
I've suggested a few changes, and also some other comments:

1. Could you change the filename to something more appropriate? Maybe `meta_repository.yml`
2. Add `fix #42` to your commit so the issue is automatically closed when this is merged. You can use `git commit --amend` and then change the message to include `fix #42`

2022-06-19 00:21 UTC, Snailedlt commented on .github/ISSUE_TEMPLATE/confiq.yml
> +      value: '## Thanks for taking the time to contribute to the repository.'
I'd like for there to be a checkbox here which asks the user to confirm that they  have searched for similar issues.
You can ofc, have this in addition to what you wrote already if you want that :) Always nice to thank contributors!
```suggestion
        value: '## Before you continue, please search our open/closed issues to see if a similar issue has been addressed.'

  - type: checkboxes
    attributes:
      label: I have searched through the issues and didn't find my problem.
      options:
        - label: Confirm
          required: true
```

2022-06-19 00:21 UTC, Snailedlt commented on .github/ISSUE_TEMPLATE/confiq.yml
> +name: meta/repository Report
Can we add this emoji here?
```suggestion
name: 📇 Meta/Repository Feature
```

2022-06-19 00:21 UTC, Snailedlt commented on .github/ISSUE_TEMPLATE/confiq.yml
> +title: "meta/ repository issue"
This is the title of the issue the user is making.

I like to put in a suggestion here which goes something like this:
```suggestion
title: "📇 <feature name>"
```

2022-06-19 00:21 UTC, Snailedlt commented on .github/ISSUE_TEMPLATE/confiq.yml
> +labels: ["updates"]
We don't have an update label, but we do have a label for 📇 Meta/Repository
```suggestion
labels: ["📇 Meta/Repository"]
```

2022-06-19 00:21 UTC, Snailedlt commented on .github/ISSUE_TEMPLATE/confiq.yml
> +      description: is there anything else that you like to comment a little on
Can we change it to this?
```suggestion
      description: is there anything else that you'd like to add?
```

2022-06-19 00:21 UTC, Snailedlt commented on .github/ISSUE_TEMPLATE/confiq.yml
> +
We can remove the extra line breaks here :)

2022-06-19 00:21 UTC, Snailedlt commented on .github/ISSUE_TEMPLATE/confiq.yml
> +      description: is there something unclear with the files ?.
Not sure what exactly you mean about this. Could you explain?

2022-06-19 00:21 UTC, Snailedlt commented on .github/ISSUE_TEMPLATE/confiq.yml
> +
```suggestion
```

2022-06-19 19:13 UTC, errorline99 commented on .github/ISSUE_TEMPLATE/confiq.yml
> +      description: is there something unclear with the files ?.
incase there is something wrong or confusing in the readme docs

2022-06-19 19:16 UTC, errorline99 commented
I think i changed everything you asked but still not sure about the git commit and how to do it

2022-06-19 20:05 UTC, Snailedlt commented on .github/ISSUE_TEMPLATE/confiq.yml
> +      description: is there something unclear with the files ?.
Okey. Could we perhaps just write something like
`Is there anything else we should know about?`

2022-06-19 20:12 UTC, Snailedlt requested changes
There's still a few things missing.
Go throuigh the suggestions I made earlier one by one, and click on `resolve` once you think you've resolved them

2022-06-19 20:12 UTC, Snailedlt commented on .github/ISSUE_TEMPLATE/meta_repository.yml
> +      value: '## Thanks for taking the time to contribute to the repository.'
I don't think it works with multiple value fields here. Try this instead
```suggestion
      value: '## Thanks for taking the time to contribute to the repository.'
  
  - type: markdown
    attributes:   
```

So the whole code snippet should look like this:
```yml
  - type: markdown
    attributes:
      value: '## Thanks for taking the time to contribute to the repository.'
  
  - type: markdown
    attributes:
      value: '## Before you continue, please search our open/closed issues to see if a similar issue has been addressed.'
```

2022-06-21 19:54 UTC, errorline99 commented on .github/ISSUE_TEMPLATE/meta_repository.yml
> +      value: '## Thanks for taking the time to contribute to the repository.'
ohhh that makes a lot of sense thank for the tip

2022-06-21 20:18 UTC, errorline99 commented
made the change. really hope it looks good now

2022-06-22 05:58 UTC, Snailedlt commented on .github/ISSUE_TEMPLATE/confiq.yml
> +name: meta/repository Report
@errorline99
This one isn't resolved yet

2022-06-22 06:03 UTC, Snailedlt requested changes
Let's see.

Everything except the title (see the comment from earlier that I marked ss unresolved), and some extra lines here and there is fixed now.
I made suggestions on each fix, so you can just click apply changes to commit them, then we're good to go :)

2022-06-22 06:03 UTC, Snailedlt commented on .github/ISSUE_TEMPLATE/meta_repository.yml
> +
```suggestion
```

2022-06-22 06:03 UTC, Snailedlt commented on .github/ISSUE_TEMPLATE/meta_repository.yml
> +
```suggestion
```

2022-06-22 06:03 UTC, Snailedlt commented on .github/ISSUE_TEMPLATE/meta_repository.yml
> +
```suggestion
```

2022-06-22 06:04 UTC, Snailedlt commented
The title suggestion: https://github.com/SplitScreen-Me/splitscreenme-discordbot/pull/44#discussion_r901029308

2022-06-22 17:48 UTC, errorline99 commented on .github/ISSUE_TEMPLATE/confiq.yml
> +name: meta/repository Report
finished it. thank you very much for explaining these stuff to me

2022-06-23 22:12 UTC, Snailedlt approved these changes
Everything except the title looks good now. I'll just change it so we can merge this in.

Thank you very much for your contribution! 💯

2022-06-23 22:12 UTC, Snailedlt commented on .github/ISSUE_TEMPLATE/meta_repository.yml
> +title: "meta/ repository issue"
```suggestion
title: "📇 Meta/Repository Feature"
```

2022-06-23 22:15 UTC, Snailedlt approved these changes
LGTM

2022-06-23 22:15 UTC, merged